#!/bin/bash

BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)

if [[ $BRANCH_NAME =~ (PPSVS-[0-9]+) ]]; then
  TICKET="${BASH_REMATCH[1]}"

  # Prefix title with ticket number
  sed -i.bak -e "0,/@/s/@/$TICKET @/" $1

  # Add issue link as trailer
  sed -i.bak -e "s/#Issue:/Issue: https:\/\/everydayhealth.atlassian.net\/browse\/$TICKET/" $1
fi
